package Domain;/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/

import javax.persistence.*;
import java.util.*;

@javax.persistence.Entity(name = "Bug")
@Table(name = "Bug")
public class Bug extends Entity {
    private String name;
    @Enumerated(EnumType.STRING)
    @Column(name = "bugImportance")
    private BugImportance bugImportance;
    @Enumerated(EnumType.STRING)
    @Column(name = "bugStatus")
    private BugStatus bugStatus;

    private String description;

    @OneToMany(
            cascade = CascadeType.ALL,
            orphanRemoval = true
            )
    private Set<BugVersion> bugVersions = new HashSet<BugVersion>();

    public Bug(String name, BugImportance bugImportance, BugStatus bugStatus, String description) {
        this.name = name;
        this.bugImportance = bugImportance;
        this.bugStatus = bugStatus;
        this.description = description;
    }

    public Bug() {

    }

    public String getName() {
        return name;
    }

    public BugImportance getBugImportance() {
        return bugImportance;
    }

    public BugStatus getBugStatus() {
        return bugStatus;
    }

    public String getDescription() {
        return description;
    }

    public Set<BugVersion> get() {
        return bugVersions;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setBugImportance(BugImportance bugImportance) {
        this.bugImportance = bugImportance;
    }

    public void setBugStatus(BugStatus bugStatus) {
        this.bugStatus = bugStatus;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void addBugVersion(BugVersion x){
        bugVersions.add(x);
    }
}