package Domain;/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/

import java.io.Serializable;
import java.util.*;
import java.time.*;




public enum BugStatus  implements Serializable {
    NEW,
    UN_RESOLVED,
    ON_GOING,
    ON_TESTING;
}