package Domain;/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/

import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import java.io.Serializable;

@Entity
@DiscriminatorValue("1")
public class Developer extends Employee  implements Serializable {
    public Developer(String username, String password, String name) {
        super(username, password, name);
    }

    public Developer() {
    }
}