package Domain;/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/

import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import java.io.Serializable;

@Entity
@DiscriminatorValue("2")
public class Tester extends Employee implements Serializable {

    public Tester(String username, String password, String name) {
        super(username, password, name);
    }

    public Tester() {
    }
}